# Generated by Django 4.1.2 on 2022-10-26 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itishaDrinks', '0002_drink_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itisha_drinks',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itishaDrinks.drink_shop'),
        ),
    ]
