# Generated by Django 4.1.2 on 2022-10-26 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itishaDrinks', '0003_alter_itisha_drinks_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='itisha_drinks',
            name='shops',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itishaDrinks.drink_shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itisha_drinks',
            name='shop',
            field=models.CharField(max_length=250),
        ),
    ]
