# Generated by Django 4.1.2 on 2022-10-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itishaDrinks', '0004_itisha_drinks_shops_alter_itisha_drinks_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itisha_drinks',
            name='shops',
        ),
        migrations.DeleteModel(
            name='drink_shop',
        ),
    ]
