# Generated by Django 4.1.2 on 2022-10-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itishaDrinks', '0005_remove_itisha_drinks_shops_delete_drink_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='itisha_drinks',
        ),
    ]
