# Generated by Django 4.1.2 on 2022-11-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itishaDrinks', '0008_drinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='drinks',
        ),
        migrations.RemoveField(
            model_name='itisha_drinks',
            name='shops',
        ),
        migrations.AddField(
            model_name='itisha_drinks',
            name='offers',
            field=models.BooleanField(default=False, help_text='clicked means it is categorised as 15% off'),
        ),
        migrations.AddField(
            model_name='itisha_drinks',
            name='recommended',
            field=models.BooleanField(default=False, help_text='clicked means it is categorised here'),
        ),
        migrations.AddField(
            model_name='itisha_drinks',
            name='top_rated',
            field=models.BooleanField(default=False, help_text='clicked means it is categorised here'),
        ),
    ]
