# Generated by Django 4.1.2 on 2022-11-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itishaDrinks', '0010_alcohol_drinks_remove_itisha_drinks_drink_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='soda_drinks',
            fields=[
                ('drink_slug', models.CharField(help_text='the names of the product SHOULD be unique to every product.', max_length=250, primary_key=True, serialize=False)),
                ('drink_type', models.CharField(help_text='this is the drink category, either alcohol, Energy drink, juice ...', max_length=250)),
                ('drink_name', models.CharField(help_text='Can be same to drink slug, (but not every time)', max_length=250)),
                ('drink_qty', models.CharField(max_length=250)),
                ('drink_price', models.IntegerField()),
                ('alcohol_drinks_type', models.CharField(choices=[('G', 'Gin'), ('W', 'Whiskey'), ('V', 'Vodka'), ('R', 'Ram')], max_length=20)),
                ('drink_description', models.CharField(max_length=250)),
                ('top_rated', models.BooleanField(default=False, help_text='categorised under the top rated category')),
                ('recommended', models.BooleanField(default=False, help_text=' recommencded to other users')),
                ('offers', models.BooleanField(default=False, help_text=' categorised as 15% off')),
            ],
        ),
        migrations.AlterField(
            model_name='alcohol_drinks',
            name='alcohol_drinks_type',
            field=models.CharField(choices=[('', 'Gin'), ('W', 'Whiskey'), ('V', 'Vodka'), ('R', 'Ram')], max_length=20),
        ),
    ]
