# Generated by Django 4.1.2 on 2022-11-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itishaDrinks', '0011_soda_drinks_alter_alcohol_drinks_alcohol_drinks_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='soda_drinks',
        ),
        migrations.RemoveField(
            model_name='alcohol_drinks',
            name='alcohol_drinks_type',
        ),
        migrations.AlterField(
            model_name='alcohol_drinks',
            name='drink_type',
            field=models.CharField(choices=[('', 'Gin'), ('W', 'Whiskey'), ('V', 'Vodka'), ('R', 'Ram')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itisha_drinks',
            name='drink_qty',
            field=models.IntegerField(help_text='the amount of drinks in store. Eg  25 '),
        ),
        migrations.AlterField(
            model_name='itisha_drinks',
            name='drink_type',
            field=models.CharField(choices=[('S', 'Soda'), ('C', 'CockTails'), ('J', 'Juices'), ('Y', 'Yorghurt')], max_length=20),
        ),
    ]
