# Generated by Django 4.1.2 on 2022-11-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itishaDrinks', '0012_delete_soda_drinks_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='itisha_drinks',
            new_name='drinks',
        ),
    ]
