# Generated by Django 4.1.2 on 2022-11-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itishaDrinks', '0013_rename_itisha_drinks_drinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='drinks',
            new_name='itisha_drinks',
        ),
    ]
