# Generated by Django 4.1.2 on 2022-11-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itishaDrinks', '0014_rename_drinks_itisha_drinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol_drinks',
            name='drink_type',
            field=models.CharField(choices=[('G', 'Gin'), ('W', 'Whiskey'), ('V', 'Vodka'), ('R', 'Ram')], max_length=20),
        ),
    ]
